[package]
edition = "2018"
name = "ra_db"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[lib]
doctest = false

[dependencies]
salsa = "0.13.0"
relative-path = "1.0.0"
rustc-hash = "1.0"

ra_syntax = { path = "../ra_syntax" }
ra_cfg = { path = "../ra_cfg" }
ra_prof = { path = "../ra_prof" }
test_utils = { path = "../test_utils" }
