[package]
edition = "2018"
name = "ra_fmt"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[lib]
doctest = false

[dependencies]
itertools = "0.8.0"

ra_syntax = { path = "../ra_syntax" }
