[package]
edition = "2018"
name = "ra_prof"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[dependencies]
once_cell = "0.2.0"
itertools = "0.8.0"
backtrace = "0.3.28"
jemallocator = { version = "0.3.2", optional = true }
jemalloc-ctl = { version = "0.3.2", optional = true }

[features]
jemalloc = [ "jemallocator", "jemalloc-ctl" ]
cpu_profiler = []
