[package]
edition = "2018"
name = "ra_project_model"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[lib]
doctest = false

[dependencies]
log = "0.4.5"
rustc-hash = "1.0"

cargo_metadata = "0.9.0"

ra_arena = { path = "../ra_arena" }
ra_db = { path = "../ra_db" }
ra_cfg = { path = "../ra_cfg" }

serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
