[package]
edition = "2018"
name = "ra_hir"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
arrayvec = "0.4.10"
log = "0.4.5"
relative-path = "0.4.0"
rustc-hash = "1.0"
parking_lot = "0.9.0"
ena = "0.13"
once_cell = "0.2"

ra_syntax = { path = "../ra_syntax" }
ra_arena = { path = "../ra_arena" }
ra_db = { path = "../ra_db" }
mbe = { path = "../ra_mbe", package = "ra_mbe" }
tt = { path = "../ra_tt", package = "ra_tt" }
test_utils = { path = "../test_utils" }
ra_prof = { path = "../ra_prof" }

chalk-solve = { git = "https://github.com/rust-lang/chalk.git" }
chalk-rust-ir = { git = "https://github.com/rust-lang/chalk.git" }
chalk-ir = { git = "https://github.com/rust-lang/chalk.git" }
lalrpop-intern = "0.15.1"

[dev-dependencies]
insta = "0.9.0"
