[package]
edition = "2018"
name = "ra_text_edit"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[lib]
doctest = false

[dependencies]
text_unit = "0.1.6"

[dependencies.proptest]
version = "0.9.0"
# Disable `fork` feature to allow compiling on webassembly
default-features = false
features = ["std", "bit-set", "break-dead-code"]

[dev-dependencies]
test_utils = { path = "../test_utils" }
