[package]
edition = "2018"
name = "xtask"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[dependencies]
walkdir = "2.1.3"
pico-args = "0.3.0"
quote = "1.0.2"
proc-macro2 = "1.0.1"
ron = "0.5.1"
serde = { version = "1.0.0", features = ["derive"] }
anyhow = "1.0.19"
