(function() {var implementors = {};
implementors["ra_arena"] = [{text:"impl&lt;ID:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"ra_arena/map/struct.ArenaMap.html\" title=\"struct ra_arena::map::ArenaMap\">ArenaMap</a>&lt;ID, T&gt;",synthetic:false,types:["ra_arena::map::ArenaMap"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"ra_arena/struct.RawId.html\" title=\"struct ra_arena::RawId\">RawId</a>",synthetic:false,types:["ra_arena::RawId"]},];
implementors["ra_db"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"ra_db/struct.FileId.html\" title=\"struct ra_db::FileId\">FileId</a>",synthetic:false,types:["ra_db::input::FileId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"ra_db/struct.SourceRootId.html\" title=\"struct ra_db::SourceRootId\">SourceRootId</a>",synthetic:false,types:["ra_db::input::SourceRootId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"ra_db/struct.CrateId.html\" title=\"struct ra_db::CrateId\">CrateId</a>",synthetic:false,types:["ra_db::input::CrateId"]},];
implementors["ra_hir"] = [{text:"impl&lt;A:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>, B:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"ra_hir/enum.Either.html\" title=\"enum ra_hir::Either\">Either</a>&lt;A, B&gt;",synthetic:false,types:["ra_hir::either::Either"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"ra_hir/struct.ErasedFileAstId.html\" title=\"struct ra_hir::ErasedFileAstId\">ErasedFileAstId</a>",synthetic:false,types:["ra_hir::source_id::ErasedFileAstId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"ra_hir/enum.Namespace.html\" title=\"enum ra_hir::Namespace\">Namespace</a>",synthetic:false,types:["ra_hir::nameres::per_ns::Namespace"]},];
implementors["ra_parser"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"ra_parser/enum.SyntaxKind.html\" title=\"enum ra_parser::SyntaxKind\">SyntaxKind</a>",synthetic:false,types:["ra_parser::syntax_kind::generated::SyntaxKind"]},];
implementors["ra_syntax"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"ra_syntax/struct.Token.html\" title=\"struct ra_syntax::Token\">Token</a>",synthetic:false,types:["ra_syntax::parsing::lexer::Token"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
