[package]
edition = "2018"
name = "ra_lsp_server"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[lib]
doctest = false

[dependencies]
threadpool = "1.7.1"
relative-path = "1.0.0"
serde_json = "1.0.34"
serde = { version = "1.0.83", features = ["derive"] }
crossbeam-channel = "0.4"
flexi_logger = "0.14.0"
log = "0.4.3"
lsp-types = { version = "0.61.0", features = ["proposed"] }
rustc-hash = "1.0"
parking_lot = "0.9.0"
jod-thread = "0.1.0"
ra_vfs = "0.5.0"
ra_syntax = { path = "../ra_syntax" }
ra_text_edit = { path = "../ra_text_edit" }
ra_ide_api = { path = "../ra_ide_api" }
lsp-server = "0.3.0"
ra_project_model = { path = "../ra_project_model" }
ra_prof = { path = "../ra_prof" }
ra_vfs_glob = { path = "../ra_vfs_glob" }

[dev-dependencies]
tempfile = "3"
test_utils = { path = "../test_utils" }

[features]
jemalloc = [ "ra_prof/jemalloc" ]
