[package]
edition = "2018"
name = "ra_mbe"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[lib]
doctest = false

[dependencies]
ra_syntax = { path = "../ra_syntax" }
ra_parser = { path = "../ra_parser" }
tt = { path = "../ra_tt", package = "ra_tt" }
rustc-hash = "1.0.0"
smallvec = "1.0.0"
log = "0.4.5"

[dev-dependencies]
test_utils = { path = "../test_utils" }
