[package]
edition = "2018"
name = "ra_batch"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
log = "0.4.5"
rustc-hash = "1.0"

ra_vfs = "0.2.0"
ra_vfs_glob = { path = "../ra_vfs_glob" }
ra_db = { path = "../ra_db" }
ra_ide_api = { path = "../ra_ide_api" }
ra_hir = { path = "../ra_hir" }
ra_project_model = { path = "../ra_project_model" }
