[package]
edition = "2018"
name = "ra_cli"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[dependencies]
pico-args = "0.3.0"
flexi_logger = "0.14.0"
indicatif = "0.13.0"

ra_syntax = { path = "../ra_syntax" }
ra_ide_api = { path = "../ra_ide_api" }
ra_batch = { path = "../ra_batch" }
ra_hir = { path = "../ra_hir" }
ra_db = { path = "../ra_db" }

[dependencies.ra_prof]
path = "../ra_prof"
# features = [ "cpu_profiler" ]
# features = [ "jemalloc" ]
