[package]
edition = "2018"
name = "gen_lsp_server"
version = "0.2.0"
authors = ["rust-analyzer developers"]
repository = "https://github.com/rust-analyzer/rust-analyzer"
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
lsp-types = "0.59.0"
log = "0.4.3"
serde_json = "1.0.34"
serde = { version = "1.0.83", features = ["derive"] }
crossbeam-channel = "0.3.5"

[dev-dependencies]
flexi_logger = "0.14.0"
